export const produkte = [
    // BURGER
    {
        id: 1,
        category: "burger",
        name: "Veggie mushroom burger",
        price: 14.0,
        img: "assets/img/veggie-burger.jpg",
        description: "Mixed salad, Tomato, Lettuce, Fried mushrooms",
    },
    {
        id: 2,
        category: "burger",
        name: "All meat burger",
        price: 15.0,
        img: "assets/img/all-meat-burger.jpg",
        description: "Beef, Bacon, Cheese, Tomato, Lettuce",
    },
    {
        id: 3,
        category: "burger",
        name: "Beef red burger",
        price: 14.0,
        img: "assets/img/beef-red-burger.jpg",
        description: "Beef, Cheese, Tomato, Lettuce, Onion",
    },
    {
        id: 4,
        category: "burger",
        name: "Big chicken burger",
        price: 15.0,
        img: "assets/img/big-chicken-burger.jpg",
        description: "Chicken, Tomato, Lettuce, Cheese, Red onion",
    },

    // PIZZA
    {
        id: 5,
        category: "pizza",
        name: "Pizza Margherita",
        price: 11.9,
        img: "assets/img/pizza-margherita.jpg",
        description: "Tomato sauce, Mozzarella, Basil",
    },
    {
        id: 6,
        category: "pizza",
        name: "Pizza Chorizo",
        price: 13.0,
        img: "assets/img/pizza-chorizo.jpg",
        description: "Tomato sauce, Mozzarella, Chorizo",
    },
    {
        id: 7,
        category: "pizza",
        name: "Funghi",
        price: 12.0,
        img: "assets/img/pizza-funghi.jpg",
        description: "Tomato sauce, Grated Mushrooms",
    },
    {
        id: 8,
        category: "pizza",
        name: "Quattro formaggi with Chicken",
        price: 14.0,
        img: "assets/img/pizza-quattro.jpg",
        description: "Mozzarella, Fontina, Gorgonzola, Parmesan, Chicken",
    },

    // SALAD
    {
        id: 9,
        category: "salad",
        name: "Warm beef arugula salad",
        price: 16.9,
        img: "assets/img/beef-salad.jpg",
        description: "Arugula, Cherry tomatoes, Beef, Honey mustard dressing",
    },
    {
        id: 10,
        category: "salad",
        name: "Mini green salad",
        price: 7.0,
        img: "assets/img/mini-salad.jpg",
        description: "Mixed lettuce, Cucumber, Carrots, Peppers, Tomatoes",
    },
    {
        id: 11,
        category: "salad",
        name: "Green salad with sea food",
        price: 16.0,
        img: "assets/img/green-salad.jpg",
        description: "Mixed lettuce, Sea food, Cherry tomatoes, Olive oil dressing",
    },
    {
        id: 12,
        category: "salad",
        name: "Vegan green salad with tofu",
        price: 14.0,
        img: "assets/img/vegan-salad.jpg",
        description: "Mixed lettuce, Cucumber, Carrots, Peppers, Tomatoes, Tofu",
    },
];
